### ISSUE TITLE
Unable to open jupyter notebook

### ISSUE THREAD

**Issue by shruti26mali** [chaimeleon-eu/CHAIMELEON-Platform#20]
I am facing an issue where I am unable to open Jupyter Notebook on newly created desktops after attempting to consolidate multiple lung/colon datasets into one desktop environment. I tried to open Jupyter Notebook, but it failed to connect and showed the error: "Unable to connect." Please see the attached image file.

![image](https://github.com/user-attachments/assets/fcc914ea-62cf-4672-a871-3d2f7acfe8e9)

However, I am able to open Jupyter Notebook on older desktops that were created earlier.

I would appreciate any insights into this issue.

**Comment by Palollo** [comment]
You can see the logs of jupyter in the path `/tmp` within your desktop.  
The jupyter service is not running due to a problem loading some configuration file. And it seems caused by some incompatibility versions in dependencies from jupyter and those from any of the packages installed by your init script (`persistent-home/init.sh`).

We have rebuilt all our images in the platform to update the packages (including jupyter). So if you try to deploy a new desktop, the new image will be used and may be the issue is fixed. Can you try?

**Comment by shruti26mali** [comment]
One of the packages installed through my `persistent-home/init.sh` script was causing the problem. It had older versions of dependencies that led to the incompatibility with Jupyter.

I excluded that package from the init script, and now Jupyter Notebook runs without any issues on the new desktop. The problem seems to be resolved with this change.

Thanks again.
